export const searchList = {
    status: 'true',
    feeds: [
        {
            id: 651310,
            title: "Women's Agenda Podcast",
            url:
                'https://feeds.acast.com/public/shows/5f578c94b2c79a47331e54ab',
            originalUrl: 'http://rss.acast.com/womens-agenda',
            link: 'https://play.acast.com/s/womens-agenda',
            description:
                'Stay Smart, Get Savy See acast.com/privacy for privacy and opt-out information.',
            author: 'Agenda Media',
            ownerName: 'Agenda Media',
            image:
                'https://assets.pippa.io/shows/5f578c94b2c79a47331e54ab/show-cover.jpg',
            artwork:
                'https://assets.pippa.io/shows/5f578c94b2c79a47331e54ab/show-cover.jpg',
            lastUpdateTime: 1600990982,
            lastCrawlTime: 1601027255,
            lastParseTime: 1600997407,
            lastGoodHttpStatusTime: 1601027255,
            lastHttpStatus: 200,
            contentType: 'application/xml; charset=utf-8',
            itunesId: null,
            generator: 'pippa.io',
            language: 'en',
            type: 0,
            dead: 0,
            crawlErrors: 2,
            parseErrors: 0,
            categories: {
                '': '',
            },
        },
        {
            id: 1028783,
            title: 'FREE AGENDA by hikaru & yamotty',
            url: 'https://anchor.fm/s/147f7150/podcast/rss',
            originalUrl: 'https://anchor.fm/s/147f7150/podcast/rss',
            link: 'https://anchor.fm/free-agenda',
            description:
                '▼このチャンネルについて\nメルカリでグロースを務めてきたヒカルと株式会社10Xの創業者&amp;代表であるYamottyがビジネスやテクノロジー、スタートアップなどをトピックに話すYouTube/Podcast「FREE AGENDA」の公式アカウントです。\n\n▼Twitter\nFREE AGENDA: https://twitter.com/free.agenda\nYamotty: https://twitter.com/yamotty3\nHikaru: https://twitter.com/hik0107',
            author: 'FREE AGENDA',
            ownerName: 'FREE AGENDA',
            image:
                'https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded_nologo/3338964/3338964-1582692345796-571ead09531bc.jpg',
            artwork:
                'https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded_nologo/3338964/3338964-1582692345796-571ead09531bc.jpg',
            lastUpdateTime: 1601011105,
            lastCrawlTime: 1601011313,
            lastParseTime: 1601011322,
            lastGoodHttpStatusTime: 1601011313,
            lastHttpStatus: 200,
            contentType: 'application/rss+xml; charset=utf-8',
            itunesId: 1501550216,
            generator: 'Anchor Podcasts',
            language: 'ja',
            type: 0,
            dead: 0,
            crawlErrors: 0,
            parseErrors: 0,
            categories: {
                '': '',
                '9': 'Business',
            },
        },
        {
            id: 97486,
            title: 'GAY AGENDA podcast',
            url:
                'http://feeds.soundcloud.com/users/soundcloud:users:572350275/sounds.rss',
            originalUrl:
                'http://feeds.soundcloud.com/users/soundcloud:users:572350275/sounds.rss',
            link: 'http://soundcloud.com/user-465171154',
            description: 'Podcast by GAY AGENDA podcast',
            author: 'GAY AGENDA podcast',
            ownerName: 'GAY AGENDA podcast',
            image:
                'http://i1.sndcdn.com/avatars-000711085084-r1oj0g-original.jpg',
            artwork:
                'http://i1.sndcdn.com/avatars-000711085084-r1oj0g-original.jpg',
            lastUpdateTime: 1600908696,
            lastCrawlTime: 1601023283,
            lastParseTime: 1600912215,
            lastGoodHttpStatusTime: 1601023283,
            lastHttpStatus: 200,
            contentType: 'application/rss+xml; charset=utf-8',
            itunesId: 1484411928,
            generator: null,
            language: 'en',
            type: 0,
            dead: 0,
            crawlErrors: 6,
            parseErrors: 0,
            categories: {
                '': '',
                '9': 'Business',
            },
        },
        {
            id: 1149968,
            title: 'The Real Agenda Network',
            url: 'https://realagenda.libsyn.com/rss',
            originalUrl: 'https://realagenda.libsyn.com/rss',
            link: 'http://www.realagenda.org',
            description:
                'The Real Agenda Network, podcasts for political change, offers a range of content which aims to inform, inspire and involve those who want a democratic, inclusive and fairer society that respects human rights and protects the planet. The focus is on fixing the fundamental problems of our time, primarily the extreme economic inequality and the unnecessary financial hardship suffered by millions everyday by developing a political agenda that moves us from here to prosperity.  That’s The Real Agenda.  www.realagenda.org',
            author: 'The Real Agenda Network',
            ownerName: 'The Real Agenda Network',
            image:
                'https://ssl-static.libsyn.com/p/assets/5/d/a/1/5da151a6d91ae87f/TRAN_logo_Aug19.jpeg',
            artwork:
                'https://ssl-static.libsyn.com/p/assets/5/d/a/1/5da151a6d91ae87f/TRAN_logo_Aug19.jpeg',
            lastUpdateTime: 1600907838,
            lastCrawlTime: 1601013195,
            lastParseTime: 1600915346,
            lastGoodHttpStatusTime: 1601013195,
            lastHttpStatus: 304,
            contentType: 'application/rss+xml; charset=utf-8',
            itunesId: 1437103761,
            generator: 'Libsyn WebEngine 2.0',
            language: 'en-gb',
            type: 0,
            dead: 0,
            crawlErrors: 0,
            parseErrors: 0,
            categories: {
                '': '',
                '9': 'Business',
            },
        },
        {
            id: 457734,
            title: 'No Hidden Agenda Podcast',
            url:
                'http://feeds.soundcloud.com/users/soundcloud:users:475750905/sounds.rss',
            originalUrl:
                'http://feeds.soundcloud.com/users/soundcloud:users:475750905/sounds.rss',
            link: 'http://soundcloud.com/user-848025748',
            description:
                'A podcast focused on Hip Hop & Life conversations with no hidden agenda. #ForTheCulture',
            author: 'No Hidden Agenda Podcast',
            ownerName: 'No Hidden Agenda Podcast',
            image:
                'http://i1.sndcdn.com/avatars-000539396766-c2hy7g-original.jpg',
            artwork:
                'http://i1.sndcdn.com/avatars-000539396766-c2hy7g-original.jpg',
            lastUpdateTime: 1600846939,
            lastCrawlTime: 1601029323,
            lastParseTime: 1600863022,
            lastGoodHttpStatusTime: 1601029323,
            lastHttpStatus: 200,
            contentType: 'application/rss+xml; charset=utf-8',
            itunesId: 1441323569,
            generator: null,
            language: 'en',
            type: 0,
            dead: 0,
            crawlErrors: 3,
            parseErrors: 0,
            categories: {
                '': '',
                '9': 'Business',
            },
        },
        {
            id: 1184649,
            title: 'The Gay Agenda YYC',
            url: 'https://anchor.fm/s/d8a485c/podcast/rss',
            originalUrl: 'https://anchor.fm/s/d8a485c/podcast/rss',
            link: 'https://anchor.fm/the-gay-agenda-yyc',
            description:
                "A podcast serving up laughs, tawdry tales and really bad life advice for Calgary's #LGBTQ2+ / #GSD Community.",
            author: 'The Gay Agenda YYC',
            ownerName: 'The Gay Agenda YYC',
            image:
                'https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded/2171663/2171663-1566171456906-04f45220190b8.jpg',
            artwork:
                'https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded/2171663/2171663-1566171456906-04f45220190b8.jpg',
            lastUpdateTime: 1601033570,
            lastCrawlTime: 1601033617,
            lastParseTime: 1601033636,
            lastGoodHttpStatusTime: 1601033617,
            lastHttpStatus: 200,
            contentType: 'application/rss+xml; charset=utf-8',
            itunesId: 1477729467,
            generator: 'Anchor Podcasts',
            language: 'en',
            type: 0,
            dead: 0,
            crawlErrors: 0,
            parseErrors: 0,
            categories: {
                '': '',
                '9': 'Business',
            },
        },
        {
            id: 192101,
            title: 'AGENDA A | Alagoas',
            url: 'https://anchor.fm/s/11a2b730/podcast/rss',
            originalUrl: 'https://anchor.fm/s/11a2b730/podcast/rss',
            link: 'www.agendaa.com.br',
            description:
                'Comentários diários do editor do portal AGENDA A, Rodrigo Cavalcante, na rádio Nova Brasil Maceió (106,5 FM). Segunda a sexta, às 7h15. www.agendaa.com.br',
            author: 'AGENDA A',
            ownerName: 'AGENDA A',
            image:
                'https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded/2858764/2858764-1600441969981-101653ca6c4bd.jpg',
            artwork:
                'https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded/2858764/2858764-1600441969981-101653ca6c4bd.jpg',
            lastUpdateTime: 1601012146,
            lastCrawlTime: 1601012190,
            lastParseTime: 1601012205,
            lastGoodHttpStatusTime: 1601012190,
            lastHttpStatus: 200,
            contentType: 'application/rss+xml; charset=utf-8',
            itunesId: 1512662482,
            generator: 'Anchor Podcasts',
            language: 'pt',
            type: 0,
            dead: 0,
            crawlErrors: 0,
            parseErrors: 0,
            categories: {
                '': '',
                '9': 'Business',
                '55': 'News',
            },
        },
        {
            id: 1166187,
            title: 'La Agenda',
            url: 'https://anchor.fm/s/2a10a70/podcast/rss',
            originalUrl: 'https://anchor.fm/s/2a10a70/podcast/rss',
            link: 'https://anchor.fm/alejandro-negron',
            description:
                'Noticias, opinión y buena conversación desde Washington, D.C. Support this podcast: https://anchor.fm/alejandro-negron/support',
            author: 'La Agenda',
            ownerName: 'La Agenda',
            image:
                'https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_nologo/341084/0a210514f1855f7f.jpeg',
            artwork:
                'https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_nologo/341084/0a210514f1855f7f.jpeg',
            lastUpdateTime: 1601014917,
            lastCrawlTime: 1601014958,
            lastParseTime: 1601014972,
            lastGoodHttpStatusTime: 1601014958,
            lastHttpStatus: 200,
            contentType: 'application/rss+xml; charset=utf-8',
            itunesId: 1457233191,
            generator: 'Anchor Podcasts',
            language: 'es',
            type: 0,
            dead: 0,
            crawlErrors: 0,
            parseErrors: 0,
            categories: {
                '': '',
                '9': 'Business',
                '55': 'News',
            },
        },
        {
            id: 346888,
            title: 'Agenda podcast',
            url: 'https://www.spreaker.com/show/3658355/episodes/feed',
            originalUrl: 'https://www.spreaker.com/show/3658355/episodes/feed',
            link: 'https://www.spreaker.com/show/agenda-podcast',
            description:
                "Agenda podcast è un approfondimento versione podcast dei temi dell'Associazione Luca Coscioni. Un'agenda per le libertà civili.",
            author: 'Agenda podcast',
            ownerName: 'Agenda podcast',
            image:
                'https://d3wo5wojvuv7l.cloudfront.net/t_rss_itunes_square_1400/images.spreaker.com/original/ccacc738b325535fc20e739645c8706b.jpg',
            artwork:
                'https://d3wo5wojvuv7l.cloudfront.net/t_rss_itunes_square_1400/images.spreaker.com/original/ccacc738b325535fc20e739645c8706b.jpg',
            lastUpdateTime: 1600443103,
            lastCrawlTime: 1601017062,
            lastParseTime: 1600446255,
            lastGoodHttpStatusTime: 1601017062,
            lastHttpStatus: 200,
            contentType: 'text/xml; charset=utf-8',
            itunesId: 1477852391,
            generator: null,
            language: 'it',
            type: 0,
            dead: 0,
            crawlErrors: 5,
            parseErrors: 0,
            categories: {
                '': '',
                '9': 'Business',
                '55': 'News',
            },
        },
        {
            id: 745124,
            title: 'Da Agenda Podcast',
            url: 'https://daagenda.blubrry.net/feed/podcast/',
            originalUrl: 'https://daagenda.blubrry.net/feed/podcast/',
            link: 'https://daagenda.blubrry.net',
            description:
                'Da Agenda is a podcast that discusses a wide variety of topics in an unbiased way and provide solution of these topics. Also, offering how we, as black people can and should benefit. Vernon and Ade will unpack weekly news and view points and give their opinions.',
            author: 'Da Agenda Podcast',
            ownerName: 'Da Agenda Podcast',
            image:
                'https://daagenda.blubrry.net/wp-content/uploads/powerpress/dagenda_1400x1400.png',
            artwork:
                'https://daagenda.blubrry.net/wp-content/uploads/powerpress/dagenda_1400x1400.png',
            lastUpdateTime: 1600437657,
            lastCrawlTime: 1601033906,
            lastParseTime: 1600439116,
            lastGoodHttpStatusTime: 1601033906,
            lastHttpStatus: 200,
            contentType: 'application/rss+xml; charset=UTF-8',
            itunesId: 1528187369,
            generator: 'https://wordpress.org/?v=5.4.2',
            language: 'en-US',
            type: 0,
            dead: 0,
            crawlErrors: 0,
            parseErrors: 0,
            categories: {
                '': '',
                '9': 'Business',
                '55': 'News',
            },
        },
        {
            id: 1097819,
            title: 'The Ignant Agenda',
            url:
                'http://feeds.soundcloud.com/users/soundcloud:users:152574982/sounds.rss',
            originalUrl:
                'http://feeds.soundcloud.com/users/soundcloud:users:152574982/sounds.rss',
            link: 'http://soundcloud.com/theignantagenda',
            description:
                'A comedically genius podcast that discusses prominent topics that impact the daily lives of millennials including but not limited to relationships, sex, parenting, and social/professional development. \nwww.theignantagenda.com',
            author: 'The Ignant Agenda',
            ownerName: 'The Ignant Agenda',
            image:
                'http://i1.sndcdn.com/avatars-000518873556-89bc3n-original.jpg',
            artwork:
                'http://i1.sndcdn.com/avatars-000518873556-89bc3n-original.jpg',
            lastUpdateTime: 1600408078,
            lastCrawlTime: 1601020404,
            lastParseTime: 1600843867,
            lastGoodHttpStatusTime: 1601020404,
            lastHttpStatus: 200,
            contentType: 'application/rss+xml; charset=utf-8',
            itunesId: 996753246,
            generator: null,
            language: 'en',
            type: 0,
            dead: 0,
            crawlErrors: 0,
            parseErrors: 0,
            categories: {
                '': '',
                '9': 'Business',
                '55': 'News',
            },
        },
        {
            id: 591522,
            title: 'Resilience Agenda Radio',
            url: 'https://feeds.buzzsprout.com/1169129.rss',
            originalUrl: 'https://feeds.buzzsprout.com/1169129.rss',
            link: '',
            description:
                'Resilience Agenda Radio is for people who want to go a step deeper in understanding mental health, well-being and the good life. Because we all have mental health, our aim is to make improving our Mental Fitness a daily, proud and commonplace ritual. We make you feel smart, challenged inspired, motivated and proud to talk about mental health in a totally new and approachable way. Each episode, we talk to experts and leaders from around the world to discover new ideas, strategies and tools for developing, improving and maintaining our Mental Fitness – the key life skill of the 21st century. Me...',
            author: 'Resilience Agenda - Hadleigh Fischer',
            ownerName: 'Resilience Agenda - Hadleigh Fischer',
            image:
                'https://storage.buzzsprout.com/variants/sfq8k4hzahvg4m1lvoix7e4k4lhj/8d66eb17bb7d02ca4856ab443a78f2148cafbb129f58a3c81282007c6fe24ff2.jpg',
            artwork:
                'https://storage.buzzsprout.com/variants/sfq8k4hzahvg4m1lvoix7e4k4lhj/8d66eb17bb7d02ca4856ab443a78f2148cafbb129f58a3c81282007c6fe24ff2.jpg',
            lastUpdateTime: 1601005731,
            lastCrawlTime: 1601017933,
            lastParseTime: 1601017935,
            lastGoodHttpStatusTime: 1601017933,
            lastHttpStatus: 200,
            contentType: 'text/xml; charset=utf-8',
            itunesId: 1519866773,
            generator: null,
            language: 'en-us',
            type: 0,
            dead: 0,
            crawlErrors: 0,
            parseErrors: 0,
            categories: {
                '': '',
                '9': 'Business',
                '55': 'News',
                '20': 'Education',
                '25': 'Self-Improvement',
                '29': 'Health',
                '30': 'Fitness',
                '33': 'Mental',
            },
        },
        {
            id: 1164061,
            title: 'The Hidden Agenda',
            url: 'https://thehiddenagenda.libsyn.com/rss',
            originalUrl: 'https://thehiddenagenda.libsyn.com/rss',
            link: 'http://thehiddenagenda.libsyn.com/website',
            description:
                "A weekly live show where Tony and Thanasi talk about stuff; except neither of them tells the other what they're going to be talking about!",
            author: 'The Hidden Agenda',
            ownerName: 'The Hidden Agenda',
            image:
                'https://ssl-static.libsyn.com/p/assets/7/5/7/b/757b3a1e1ddfa161/logo_fb.jpg',
            artwork:
                'https://ssl-static.libsyn.com/p/assets/7/5/7/b/757b3a1e1ddfa161/logo_fb.jpg',
            lastUpdateTime: 1600662625,
            lastCrawlTime: 1601017749,
            lastParseTime: 1600931024,
            lastGoodHttpStatusTime: 1601017749,
            lastHttpStatus: 304,
            contentType: 'application/rss+xml; charset=utf-8',
            itunesId: 1454798535,
            generator: 'Libsyn WebEngine 2.0',
            language: 'en',
            type: 0,
            dead: 0,
            crawlErrors: 0,
            parseErrors: 0,
            categories: {
                '': '',
                '9': 'Business',
                '55': 'News',
                '20': 'Education',
                '25': 'Self-Improvement',
                '29': 'Health',
                '30': 'Fitness',
                '33': 'Mental',
            },
        },
        {
            id: 1189667,
            title: 'The Bisexual Agenda',
            url:
                'http://feeds.soundcloud.com/users/soundcloud:users:706169893/sounds.rss',
            originalUrl:
                'http://feeds.soundcloud.com/users/soundcloud:users:706169893/sounds.rss',
            link:
                'https://podcasts.apple.com/gb/podcast/the-bisexual-agenda/id1482137053',
            description:
                'A bi-weekly podcast from your local bisexual who literally can’t stop talking 🌈 Bisexuals to the front - everyone is welcome 🌈🥰 Queer-themed nonsense, tarot readings and Sagittarius charm, with a different guest every episode!',
            author: 'The Bisexual Agenda',
            ownerName: 'The Bisexual Agenda',
            image:
                'http://i1.sndcdn.com/avatars-000700320649-c44ab8-original.jpg',
            artwork:
                'http://i1.sndcdn.com/avatars-000700320649-c44ab8-original.jpg',
            lastUpdateTime: 1599502529,
            lastCrawlTime: 1601026719,
            lastParseTime: 1600959763,
            lastGoodHttpStatusTime: 1601026719,
            lastHttpStatus: 200,
            contentType: 'application/rss+xml; charset=utf-8',
            itunesId: 1482137053,
            generator: null,
            language: 'en',
            type: 0,
            dead: 0,
            crawlErrors: 0,
            parseErrors: 0,
            categories: {
                '': '',
                '9': 'Business',
                '55': 'News',
                '20': 'Education',
                '25': 'Self-Improvement',
                '29': 'Health',
                '30': 'Fitness',
                '33': 'Mental',
            },
        },
        {
            id: 670132,
            title: 'Agenda AMEXME Riviera Maya ',
            url: 'https://anchor.fm/s/209f57c0/podcast/rss',
            originalUrl: 'https://anchor.fm/s/209f57c0/podcast/rss',
            link: 'www.amexmerivieramaya.org',
            description:
                'Bienvenidos a "Agenda AMEXME Riviera Maya", por medio de este podcast queremos darles a conocer las acciones que el Consejo Directivo está y estará llevando a cabo durante este año 2020, con la finalidad de que las socias  puedan acercarse a participar con iniciativas, sugerencias constructivas y edificantes para todas. ¡Acompáñanos!',
            author: 'Agenda Amexme',
            ownerName: 'Agenda Amexme',
            image:
                'https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded_nologo/5373136/5373136-1589142241534-0d2efb1d393e2.jpg',
            artwork:
                'https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded_nologo/5373136/5373136-1589142241534-0d2efb1d393e2.jpg',
            lastUpdateTime: 1601031392,
            lastCrawlTime: 1601031427,
            lastParseTime: 1601031441,
            lastGoodHttpStatusTime: 1601031427,
            lastHttpStatus: 200,
            contentType: 'application/rss+xml; charset=utf-8',
            itunesId: 1514691014,
            generator: 'Anchor Podcasts',
            language: 'es',
            type: 0,
            dead: 0,
            crawlErrors: 0,
            parseErrors: 0,
            categories: {
                '': '',
                '9': 'Business',
                '55': 'News',
                '20': 'Education',
                '25': 'Self-Improvement',
                '29': 'Health',
                '30': 'Fitness',
                '33': 'Mental',
            },
        },
        {
            id: 50027,
            title: 'Bass Agenda',
            url:
                'http://feeds.soundcloud.com/users/soundcloud:users:381839/sounds.rss',
            originalUrl:
                'http://feeds.soundcloud.com/users/soundcloud:users:381839/sounds.rss',
            link: 'https://www.bassagenda.co.uk/',
            description:
                "Bass Agenda: Underground Electro and Techno Radio Show and Record Label\n\nThe radio show broadcasts via Juan Atkins' radio station Deepspace Radio weekly on Friday at 15:00 (Detroit) 20:00 (UK) 21:00 (CET)\n\nShowcasing the diversity, talent and influences of artists in the broad spectrums that are the Electro & Techno genres: past, present and future. Since 2012 Bass Agenda has asked artists to choose tracks important to them and has featured Interviews, guest mixes, and live sets from a diverse range of talent including Juan Atkins, Bass Junkie, Helena Hauff, The Egyptian Lover, Jensen Interceptor, Legowelt, Dave Clarke, David Meiser, Adult., Keith Tucker, Detroit In...",
            author: 'Bass Agenda',
            ownerName: 'Bass Agenda',
            image:
                'http://i1.sndcdn.com/avatars-yYcR6Q1xKANpvqIG-ebPing-original.jpg',
            artwork:
                'http://i1.sndcdn.com/avatars-yYcR6Q1xKANpvqIG-ebPing-original.jpg',
            lastUpdateTime: 1599298608,
            lastCrawlTime: 1601027330,
            lastParseTime: 1600096865,
            lastGoodHttpStatusTime: 1601027330,
            lastHttpStatus: 200,
            contentType: 'application/rss+xml; charset=utf-8',
            itunesId: 1090030497,
            generator: null,
            language: 'en',
            type: 0,
            dead: 0,
            crawlErrors: 27,
            parseErrors: 0,
            categories: {
                '': '',
                '9': 'Business',
                '55': 'News',
                '20': 'Education',
                '25': 'Self-Improvement',
                '29': 'Health',
                '30': 'Fitness',
                '33': 'Mental',
            },
        },
    ],
}

export const recentList = {
    status: 'true',
    items: [
        {
            id: 370552378,
            title: 'When I Am Older',
            link:
                'http://www.sermonaudio.com/sermoninfo.asp?SID=92420113353686',
            description: '',
            guid:
                'http://www.sermonaudio.com/sermoninfo.asp?SID=92420113353686',
            datePublished: 1600950960,
            datePublishedPretty: 'September 24, 2020 7:36am',
            dateCrawled: 1600947688,
            enclosureUrl:
                'https://mp3.sermonaudio.com/filearea/92420113353686/92420113353686.mp3',
            enclosureType: 'audio/mpeg',
            enclosureLength: 16925603,
            explicit: 0,
            episode: null,
            episodeType: null,
            season: 0,
            image:
                'https://www.sermonaudio.com/images/sermonaudio-new-combo2-1400.jpg',
            feedItunesId: 1456605946,
            feedImage:
                'https://www.sermonaudio.com/images/sermonaudio-new-combo2-1400.jpg',
            feedId: 1165765,
            feedTitle: 'SermonAudio: MP3',
            feedLanguage: 'en-us',
        },
        {
            id: 370537064,
            title: 'Life of Messiah Part 7, "Who Needs a Man?"',
            link: 'http://www.sermonaudio.com/sermoninfo.asp?SID=9242016452399',
            description: '',
            guid: 'http://www.sermonaudio.com/sermoninfo.asp?SID=9242016452399',
            datePublished: 1600950900,
            datePublishedPretty: 'September 24, 2020 7:35am',
            dateCrawled: 1600947447,
            enclosureUrl:
                'https://mp3.sermonaudio.com/filearea/9242016452399/9242016452399.mp3',
            enclosureType: 'audio/mpeg',
            enclosureLength: 13719707,
            explicit: 0,
            episode: null,
            episodeType: null,
            season: 0,
            image:
                'https://www.sermonaudio.com/images/sermonaudio-new-combo2-1400.jpg',
            feedItunesId: 1471892230,
            feedImage:
                'https://www.sermonaudio.com/images/sermonaudio-new-combo2-1400.jpg',
            feedId: 1178749,
            feedTitle: 'SermonAudio: MP3',
            feedLanguage: 'en-us',
        },
        {
            id: 370860546,
            title: '第113回「メインネット迫るFilecoinがWeb3.0時代を切り開く',
            link: 'http://nextmoney.jp/pod/?p=443',
            description:
                '第113回「メインネット迫るFilecoinがWeb3.0時代を切り開く ◆目次 ◯9月相場まとめ ◯DeFi … <p >"第113回「メインネット迫るFilecoinがWeb3.0時代を切り開く" の続きを読む</p>',
            guid: 'http://nextmoney.jp/pod/?p=443',
            datePublished: 1600950706,
            datePublishedPretty: 'September 24, 2020 7:31am',
            dateCrawled: 1600950809,
            enclosureUrl:
                'http://media.blubrry.com/aignet/aig2.xsrv.jp/nextmoney/113.MP3',
            enclosureType: 'audio/mpeg',
            enclosureLength: 91120038,
            explicit: 0,
            episode: null,
            episodeType: null,
            season: 0,
            image: '',
            feedItunesId: 1250824243,
            feedImage:
                'http://nextmoney.jp/pod/wp-content/uploads/powerpress/nextmoney.jpg',
            feedId: 1120811,
            feedTitle: '仮想通貨週刊ニュース',
            feedLanguage: 'ja',
        },
        {
            id: 370879836,
            title:
                '[Podcast] Istenélmények sallang nélkül 9. – A reklámszakma csúcsán – keresztényként',
            link:
                'https://anchor.fm/kepmaspodcast/episodes/Podcast-Istenlmnyek-sallang-nlkl-9---A-reklmszakma-cscsn--keresztnyknt-ek3qib',
            description:
                '<p>Vendégem Juhász Péter Tibor, a hazai marketingkommunikációs szakma koronázott királya. Munkáját több itthoni és nemzetközi díjjal jutalmazták, ezek közül kiemelkedik a cannes-i Arany Oroszlán-díj, amelyet a kommunikációs szakma Oscarjaként tartanak számon, ezzel a díjjal többször is elismerték tevékenységét. Pályáját olyan cégeknél építette, mint a Procter and Gamble, a Magyar Telekom és a Borsodi Sörgyár, jelenleg pedig a Vodafone Hungary márkaigazgatója. A multicégek nem feltétlenül a keresztény é...',
            guid: '180ed1d3-af4d-4110-b6ac-18cf36de384f',
            datePublished: 1600950672,
            datePublishedPretty: 'September 24, 2020 7:31am',
            dateCrawled: 1600951000,
            enclosureUrl:
                'https://anchor.fm/s/dc5f03c/podcast/play/20097035/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2020-8-24%2F8c8c921a-3ee0-f2e0-1262-1ba33e4f33d1.mp3',
            enclosureType: 'audio/mpeg',
            enclosureLength: 36112200,
            explicit: 0,
            episode: null,
            episodeType: 'full',
            season: 0,
            image:
                'https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded_episode/2210759/2210759-1600950680996-8d109621b39ac.jpg',
            feedItunesId: 1482959517,
            feedImage:
                'https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded/2210759/2210759-1570006091311-73a47351754d2.jpg',
            feedId: 96209,
            feedTitle: 'Képmás podcast',
            feedLanguage: 'hu',
        },
        {
            id: 370857755,
            title: 'La Cámara de los Balones (24/09/2020)',
            link: '',
            description:
                'La actualidad deportiva tratada con humor por Julio Muñoz, Juan Amodeo, Luis Márquez y Fran Ronquillo',
            guid:
                'https://prisa-es.mc.tritondigital.com/RADIO_JODAR_CADENASER_727_P/media/2020/9/24/ser_andalucia_lacamaradelosbalones_20200924_134500_140000.mp3',
            datePublished: 1600950607,
            datePublishedPretty: 'September 24, 2020 7:30am',
            dateCrawled: 1600950768,
            enclosureUrl:
                'https://prisa-es.mc.tritondigital.com/RADIO_JODAR_CADENASER_727_P/media/2020/9/24/ser_andalucia_lacamaradelosbalones_20200924_134500_140000.mp3',
            enclosureType: 'audio/mpeg',
            enclosureLength: 7199809,
            explicit: 0,
            episode: null,
            episodeType: null,
            season: 0,
            image:
                'https://recursosweb.prisaradio.com/fotos/original/010002775780.png',
            feedItunesId: 1122665327,
            feedImage:
                'https://cadenaser.com/estaticos/recursosgraficos/podcast/radio_jodar_podcast_3000x3000.jpg',
            feedId: 1048003,
            feedTitle: 'Radio Jódar',
            feedLanguage: 'es-ES',
        },
        {
            id: 370858994,
            title: 'Collaboration with Canadian Medical Hall of Fame (CMHF)',
            link:
                'https://www.spreaker.com/user/multipotentmd/collaboration-with-canadian-medical-hall',
            description:
                "This week's episode is just a quick update on what's to come from our collaboration with the Canadian Medical Hall of Fame. Starting next week, we will be releasing episodes for two new series: (1) Laureate Edition and (2) Medical Student Award Recipient Edition. Stay tuned!",
            guid: 'https://api.spreaker.com/episode/41066137',
            datePublished: 1600950605,
            datePublishedPretty: 'September 24, 2020 7:30am',
            dateCrawled: 1600950782,
            enclosureUrl:
                'https://api.spreaker.com/download/episode/41066137/cmhf_introduction_rendered_mp3.mp3',
            enclosureType: 'audio/mpeg',
            enclosureLength: 23467362,
            explicit: 0,
            episode: null,
            episodeType: 'full',
            season: 4,
            image:
                'https://d3wo5wojvuv7l.cloudfront.net/t_rss_itunes_square_1400/images.spreaker.com/original/bef4a7ccc78732f86475d9d372d15ddb.jpg',
            feedItunesId: 1479723036,
            feedImage:
                'https://d3wo5wojvuv7l.cloudfront.net/t_rss_itunes_square_1400/images.spreaker.com/original/4c030d3be1eeefb5af45c7cde8555acf.jpg',
            feedId: 93618,
            feedTitle: 'Multipotent MD',
            feedLanguage: 'en',
        },
        {
            id: 370857805,
            title: 'Hoy por Hoy La Rioja (24/09/2020)',
            link: '',
            description: 'Magazine de ocio, actualidad y cultura de La Rioja',
            guid:
                'https://prisa-es.mc.tritondigital.com/RADIO_RIOJA_CADENASER_1186_P/media/2020/9/24/cadenaser_la_rioja_hoyporhoylarioja_20200924_122000_140000.mp3',
            datePublished: 1600950558,
            datePublishedPretty: 'September 24, 2020 7:29am',
            dateCrawled: 1600950768,
            enclosureUrl:
                'https://prisa-es.mc.tritondigital.com/RADIO_RIOJA_CADENASER_1186_P/media/2020/9/24/cadenaser_la_rioja_hoyporhoylarioja_20200924_122000_140000.mp3',
            enclosureType: 'audio/mpeg',
            enclosureLength: 36000117,
            explicit: 0,
            episode: null,
            episodeType: null,
            season: 0,
            image:
                'https://recursosweb.prisaradio.com/fotos/original/010002653016.png',
            feedItunesId: 1442275391,
            feedImage:
                'https://cadenaser.com/estaticos/recursosgraficos/podcast/radio_rioja_portada_podcast.jpg',
            feedId: 1004587,
            feedTitle: 'Radio Rioja',
            feedLanguage: 'es-ES',
        },
    ],
    count: 7,
    max: '7',
    description: 'Found matching items.',
}
