name: Validate JSONs

on:
  push:
    branches: [ master ]
    paths:
      - 'server/data/**.json'
  pull_request:
    branches: [ master ]
    paths:
      - 'server/data/**.json'
  workflow_dispatch:

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Validate JSON
        uses: dsanders11/json-schema-validate-action@eddf079f55830cc9a916a3c512ba9086240d2fea # v2.0.0
        with:
          schema: ./server/data/apps-schema.json
          files: ./server/data/apps.json

# https://github.com/marketplace/actions/json-schema-validate
# Alternative
# https://github.com/OrRosenblatt/validate-json-action
